### ISSUE TITLE
send_emails.py does not work

### ISSUE THREAD

**Issue by spinning-fantasies** [spinning-fantasies/secret-santa#1]
First it seems sending emails is working but finally it does not.

```python
Traceback (most recent call last):
  File "/Users/mathieu/Code/Python/secret-santa/send_emails.py", line 61, in <module>
    send_email(sender_email, sender_password)
  File "/Users/mathieu/Code/Python/secret-santa/send_emails.py", line 51, in send_email
    server.sendmail(sender_email, participant_email, message.as_string())
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (421, b'Server disconnection', 'leperenoel@mailo.com')

```

**Comment by spinning-fantasies** [comment]
See https://github.com/spinning-fantasies/ChatGPT-Python-Snippets/issues/1
